### ISSUE TITLE
Prepper Clean Architecture

### ISSUE THREAD

**Issue by amirrezavaladkhani** [McProgrammer1/McProgrammer1#1]

**Comment by amirrezavaladkhani** [comment]
بنظرت درست پیاده سازی شده؟؟

**Comment by mc-programmer** [comment]
واستا ببینم

**Comment by mc-programmer** [comment]
نیومده 404 میده

**Comment by amirrezavaladkhani** [comment]
https://github.com/amirrezavaladkhani/CSC-Blog/invitations

**Comment by amirrezavaladkhani** [comment]
https://github.com/amirrezavaladkhani/CSC-Blog

**Comment by amirrezavaladkhani** [comment]
یه بار دیگه چک کن

**Comment by mc-programmer** [comment]
چک کرم
چند تا کار هست که باید انجام بدی
1. CSCBlog رو که لایه presentation هست رو بکن 
CSCBlog.Web
این وب رو بهش اضافه کن

2. CSCBlog.Infrastructure رو بکن 
CSCBlog.Infra.Data

درستش کردی اطلاع بده

**Comment by amirrezavaladkhani** [comment]
مجدد تغییرات اعمال شد

**Comment by amirrezavaladkhani** [comment]
https://raw.githubusercontent.com/dotnet-architecture/eBooks/main/current/architecting-modern-web-apps-azure/Architecting-Modern-Web-Applications-with-ASP.NET-Core-and-Azure.pdf
این pdf بنظرت مفیده؟؟

**Comment by mc-programmer** [comment]
لایه ioc رو قورت دادی؟  😂

**Comment by amirrezavaladkhani** [comment]
گشنم شدش خوردمش

**Comment by amirrezavaladkhani** [comment]
Cscblog.ioc?

**Comment by amirrezavaladkhani** [comment]
تغیراتو اضافه کردمش

**Comment by amirrezavaladkhani** [comment]
یه چک بکن

**Comment by mc-programmer** [comment]
اوکی

**Comment by amirrezavaladkhani** [comment]
تمام؟؟

**Comment by mc-programmer** [comment]
حله الان تسک بعدی رو بهت میدم
