### ISSUE TITLE
Add BaseEntity Model To Project

### ISSUE THREAD

**Issue by amirrezavaladkhani** [McProgrammer1/McProgrammer1#2]

**Comment by amirrezavaladkhani** [comment]
description required

**Comment by mc-programmer** [comment]
### مدل به این شکل باشه
<hr/>
Base entity<T> <br>
T Id <br>
CreateDate
<hr>

### باید اول تحقیق کنی

**Comment by amirrezavaladkhani** [comment]
Task Completed

**Comment by amirrezavaladkhani** [comment]
https://github.com/amirrezavaladkhani/CSC-Blog

**Comment by mc-programmer** [comment]
چند تا مشکل وجود داره
اولا من مدل یوزر ازت نخواستم اونو پاک کن
دوما base entity رو داخل پوشه ای به نام common بزار
من ازت update at نخواسته بودم اونو پاک کن

**Comment by mc-programmer** [comment]
در ضمن end date رو تو نزار من باید بزارم به خاطر اینکه مطمئن بشم تسک رو بلدی

**Comment by amirrezavaladkhani** [comment]
حالا یکم رفتم جلو :(

**Comment by mc-programmer** [comment]
BaseEntity<T>
[Key]
public T Id{ get; set ;}
public DateTime CreateDate{get;set;} = DateTime.Now();

**Comment by amirrezavaladkhani** [comment]
بی جنبه تموم شد

**Comment by amirrezavaladkhani** [comment]
(￣o￣) . z Z

**Comment by mc-programmer** [comment]
منظورت از بی جنبه چیه؟

**Comment by mc-programmer** [comment]
چیزی میگم برای اینکه برات ارزش قائلم ، کاش یکی بود کاربلد بود ایراد کار منم میگرفت
اگه ناراحت میشی دیگه سخت گیری نکنم بزارم هر کاری دوست داری بکنی
