### ISSUE TITLE
Add User Model

### ISSUE THREAD

**Issue by mc-programmer** [McProgrammer1/McProgrammer1#3]
اطلاعات مورد نیاز برای شروع
منظور از ؟ نال پذیر بودنه همون طور که میدونی

User : baseentity <int>
FirstName? 300 character
LastName? 300 character
Email 300 character

IsDelete
IsEmailActive
EmailActivationCode

**Comment by amirrezavaladkhani** [comment]
تمام شد

**Comment by mc-programmer** [comment]
الان نگاه میکنم

**Comment by mc-programmer** [comment]
دیدمش افرین سعی کن از {0} هم استفاده کنی

**Comment by mc-programmer** [comment]
سعی کن مدل یوزر رو داخل پوشه ای به نام User بزاری
