### ISSUE TITLE
Switch Git Hub project

### ISSUE THREAD

**Issue by amirrezavaladkhani** [McProgrammer1/McProgrammer1#4]
یک GitHub Project جدید ایجاد کن و ادامه تسک ها رو در اون جا میزاریم

https://www.linkedin.com/groups/12829763/
اینم از انجمنمون تو گیتهاب که 6 تا ممبر داره تا الان 😊

**Comment by amirrezavaladkhani** [comment]
تمام

**Comment by amirrezavaladkhani** [comment]
https://github.com/users/amirrezavaladkhani/projects

**Comment by mc-programmer** [comment]
ایول افرین

**Comment by mc-programmer** [comment]
پس من دیگه این پروجکت رو ببندم
